### PR TITLE
Change view design from dark to light

### PR DESCRIPTION
**Pull request by jancborchardt**
@LukasReschke for some reason the CSS isn’t updated. To I need to compile something? (If so, we should add that to the readme.)

### CODE REVIEW

**Comment by LukasReschke** [comment]
> @LukasReschke for some reason the CSS isn’t updated. To I need to compile something? (If so, we should add that to the readme.)

Define "the CSS"

**Comment by jancborchardt** [comment]
@LukasReschke the changes I made. Do you see them?

**Comment by jancborchardt** [comment]
@nextcloud/designers you want to check this out?

**Comment by MorrisJobke** [comment]
👎 no header bar for closing the PDF is missing

**Comment by MorrisJobke** [comment]
please rebase

**Comment by jancborchardt** [comment]
Rebased and fixed some last details. Ready to review @nextcloud/designers @nextcloud/javascript @LukasReschke @MorrisJobke

**Comment by MorrisJobke** [comment]
Doesn't work with IE11 and Edge:

bildschirmfoto 2016-11-16 um 11 24 11 2

**Comment by jancborchardt** [comment]
TODO:
- [ ] to make it work in IE, manually color-invert all icons instead of using CSS inversion, and then override the originals via CSS :unamused:

**Comment by MariusBluem** [comment]
What is the current state here?

**Comment by MorrisJobke** [comment]
> What is the current state here?

I guess it's "abandoned" -.-

**Comment by MorrisJobke** [comment]
Nothing for 12 -> moved to 13.

**Comment by MorrisJobke** [comment]
Moved to 14.

**Comment by jancborchardt** [comment]
@juliushaertl @skjnldsv as you are more knowledgeable about the whole color inversion stuff, do you have any idea here?

**Comment by MorrisJobke** [comment]
Moved to 15

**Comment by juliushaertl** [comment]
This is nothing that will be done til tomorrow so I'd say we move it to 16, but I'll look into it.

**Comment by jancborchardt** [comment]
For reference, these are the related issues in Mozilla’s PDF.js repository:
- Themes & Skins for pdf.js https://github.com/mozilla/pdf.js/issues/3528
- Replace PNG assets with SVG assets https://github.com/mozilla/pdf.js/issues/6252

They seem welcoming towards contributions for theming, and lots of people ask for it. So if we do something here it might be good to look at upstreaming it. @juliushaertl let’s sit together at the Contributor Week?

**Comment by skjnldsv** [comment]
OUtdated

**Pull request closed without merging**
