### PR TITLE
Fix unknown variable after upgrade from v2.13.216

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix https://github.com/nextcloud/server/issues/31795

Ref https://github.com/mozilla/pdf.js/releases/tag/v2.13.216

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
can you do a new release ? @skjnldsv 

I guess it will be compatible with older stable versions

**Comment by skjnldsv** [comment]
> can you do a new release ? @skjnldsv
> 
> I guess it will be compatible with older stable versions

This is shipped

**Pull request merged**
