### PR TITLE
fix pdf-viewer sizing

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/files_pdfviewer/issues/843

| Before | After |
|---|---|
| image | image |

### CODE REVIEW

**Review by danxuliu — DISMISSED** [review]
Blocking at least until https://github.com/nextcloud/viewer/pull/2030 is clarified.

**Comment by skjnldsv** [comment]
How does it behaves with the sidebar or other menus?

**Comment by szaimen** [comment]
> How does it behaves with the sidebar or other menus?

Works:
image

**Review by skjnldsv — APPROVED** [review]
🫡

**Review by danxuliu — COMMENTED** [review]
I am late to the party, but... tested and works :+1:

Nice fix :-D

**Pull request merged**
