### PR TITLE
Fix pdfviewer design

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/files_pdfviewer/issues/279
Fix https://github.com/nextcloud/files_pdfviewer/issues/238

## Desktop
| Before | After | After with sidebar open |
|---|---|---|
| image | image | image |

## Mobile
| Before | Before | After |
|---|---|---|
| image | image | image |

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by szaimen** [comment]
Hm... not sure why `/compile amend /` fails. Any idea @skjnldsv ?

**Comment by szaimen** [comment]
@skjnldsv I suppose that those values would need to get modified, too? https://github.com/nextcloud/files_pdfviewer/blob/8ceea610a2f16fceb9f034719ae73676400c398c/src/public.js#L50-L51

**Comment by szaimen** [comment]
@beardhatcode do you mind compiling and pushing the js? I am currently not able to do so. Thank you! :)

**Review by Pytal — APPROVED** [review]

**Review by artonge — APPROVED** [review]
Nice !

**Comment by szaimen** [comment]
Thanks @artonge for compiling and pushing the js! :)

**Comment by jancborchardt** [comment]
Yeeessss full width and to the bottom! :D Nice work!

**Pull request merged**
