### PR TITLE
update to pdf.js 2.6.347

### PR DESCRIPTION
**Pull request by salcromic**
update pdf.js: 2.4.456 to 2.6.347

### CODE REVIEW

**Comment by skjnldsv** [comment]
Hi, It's not as easy, Mozilla changed their release content and our app needs to adapt to it.

**Comment by skjnldsv** [comment]
See https://github.com/nextcloud/files_pdfviewer/pull/225

**Comment by skjnldsv** [comment]
ALso, v2.6.347 is not released as stable yet

**Comment by salcromic** [comment]
Hi, does the update 2.5.207 in Nextcloud support interactive PDFs (edit and save in browser)? This would be very very important to me, I would also like to support this financially.

**Comment by skjnldsv** [comment]
I can't tell. You need to check the changelog of pdf.js https://github.com/mozilla/pdf.js/releases

**Pull request closed without merging**
