### PR TITLE
Setup Transifex translations

### PR DESCRIPTION
**Pull request by danxuliu**
Until recently all the strings shown in the UI came from PDF.js, and they used its localisation system. However, [now there are some strings specific to the Nextcloud PDF viewer](https://github.com/nextcloud/files_pdfviewer/pull/787/commits/f4417bbd4fcb28841f828189d5a72a9a9ff145f7#diff-84f92d7129f879a2f201fbc32ac9281b7a84dc921ea4a1ba2754788046234b3aR139), so they need to be explicitly translated using the Nextcloud translation system.

Changes based on https://docs.nextcloud.com/server/27/developer_manual/basics/front-end/l10n.html#adding-translations; pull request in https://github.com/nextcloud/docker-ci to be done once this one is merged.

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
Changes look good based on the docs but did not test and don't have any experience with our l10n translation. So maybe better e.g. Joas should review this?

**Comment by nickvergessen** [comment]
If you follow the issue template I can help :) 
https://github.com/nextcloud/docker-ci/issues/new/choose

**Comment by danxuliu** [comment]
> If you follow the issue template I can help :) https://github.com/nextcloud/docker-ci/issues/new/choose

Cool, thanks :-)

Template added in https://github.com/nextcloud/docker-ci/issues/604

I have noticed that `lang_map` values have a different sorting in [the documentation](https://github.com/nextcloud/documentation/blob/0323857b2d24bdcdb4cd277153065f8c44b89819/developer_manual/basics/front-end/l10n.rst?plain=1#L281) and in [the _Request translations_ template](https://github.com/nextcloud/docker-ci/blob/a83b06b15c4fd861f5716735f5c2e6fd894de057/.github/ISSUE_TEMPLATE/---request-translations.md?plain=1#L30), so the file _.tx/config_ in this pull request does not exactly match the template. However, although the sorting is different, the values are the same.

Similarly, the documentation says that `nextcloud-bot` [should get write access to the repository](https://github.com/nextcloud/documentation/blob/0323857b2d24bdcdb4cd277153065f8c44b89819/developer_manual/basics/front-end/l10n.rst?plain=1#L295-L298), but the template says that it is only needed [if the app is not in the Nextcloud organisation](https://github.com/nextcloud/docker-ci/blob/a83b06b15c4fd861f5716735f5c2e6fd894de057/.github/ISSUE_TEMPLATE/---request-translations.md?plain=1#L17).

Finally, for now there are no translatable strings in the _stableXX_ branches, only in _master_. I guess that is not a problem and the bot will simply ignore the _stableXX_ branches, but I mention it just in case a `.tx/backport` file is needed to avoid processing the _stableXX_ branches.

**Comment by nickvergessen** [comment]
> .tx/backport

Yes you should create it and then add each stable branch until it matches upstream. So for now add stable28 already, and then with stable30 being added you can drop the file

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
Ah, info.xml is also translated, so we could just remove the backport file already then it's not forgotten

**Pull request merged**
