### PR TITLE
[stable22] disable scripting in pdfviewer

### PR DESCRIPTION
**Pull request by szaimen**
Manual backport of https://github.com/nextcloud/files_pdfviewer/pull/887 to stable22

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]

**Comment by szaimen** [comment]
library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'

**Comment by szaimen** [comment]
@nickvergessen sorry for pinging you but would you mind trying to compile the js here and commiting it? Possibly it will fail with the same issue though... Thanks for your help! :)

**Comment by nickvergessen** [comment]
Did that, but CI in here will still be red, but I guess you can force merge?

**Comment by szaimen** [comment]
> Did that, but CI in here will still be red, but I guess you can force merge?

yes, thanks for compiling! :)

**Comment by szaimen** [comment]
CI failure unrelated

**Pull request merged**
