### PR TITLE
Allow pdfviewer to open illustrator (.ai) files

### LINKED ISSUE #162: Please make files_pdfviewer the default app for opening illustrator files (.ai)
In my experience, many Illustrator files (.ai) can get opened with a pdf reader because they are compatible. So why not making this app to the default also for opening .ai files?
(to my knowledge Illustrator files otherwise cannot get opened or shown in the Nextcloud universe today)
(the best proof was, that I renamed a .ai file to a .pdf file and opened it with the pdfviewer -> it worked.)

### PR DESCRIPTION
**Pull request by szaimen**
Signed-off-by: szaimen <szaimen@e.mail.de>

Should fix #162

### CODE REVIEW

**Comment by szaimen** [comment]
Hm... Does somwone know why some tests are failing? This shouldn't theoretically effect any test, does it?

**Comment by skjnldsv** [comment]
Maybe we should also update the Readme and the app description?

**Comment by skjnldsv** [comment]
> Hm... Does somwone know why some tests are failing? This shouldn't theoretically effect any test, does it?

you need to compile the app and sjip the changed files (thus my compile comment)

**Comment by skjnldsv** [comment]
Please open a pr to update the readme and the app info.xml description?

**Comment by szaimen** [comment]
> Maybe we should also update the Readme and the app description?

Hm, maybe yes? I mean it is somehow a cool feature ;)

**Comment by szaimen** [comment]
> Please open a pr to update the readme and the app info.xml description?

I am not the best in advertising new features but I'll give it a try! :)

**Pull request merged**
