### PR TITLE
[master] Fix npm audit

### PR DESCRIPTION
**Pull request by nextcloud-command**
Auto-generated fix of npm audit

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
LGTM but didnt test

**Review by danxuliu — COMMENTED** [review]
UI is broken. However, this seems to be unrelated and to have been caused by https://github.com/nextcloud/files_pdfviewer/pull/762, as rebuilding with node 16 fixes the UI. Therefore, I would merge as is and leave the UI fix for a later pull request.

**Pull request merged**
