### PR TITLE
Bump pdf.js to 2.6.347

### PR DESCRIPTION
**Pull request by skjnldsv**
Functional
- [x] Waiting for [2.6.347](https://github.com/mozilla/pdf.js/releases/tag/v2.6.347) to be released as stable

### CODE REVIEW

**Comment by salcromic** [comment]
Nice :]. Thanks

**Comment by salcromic** [comment]
I hope the full version will come out soon - so that in the future you can edit interactive pdfs in the cloud, in the browser. :)

**Comment by szaimen** [comment]
@skjnldsv 2.6.347 is the latest release now :)
https://github.com/mozilla/pdf.js/releases/tag/v2.6.347

**Comment by salcromic** [comment]
Yaaaaa, I'm excited :)

**Comment by salcromic** [comment]
when is nextcloud 22 coming out?

**Comment by szaimen** [comment]
> when is nextcloud 22 coming out?

Probably mid 2021

**Comment by skjnldsv** [comment]
Good to go for me :+1:

**Comment by salcromic** [comment]
@skjnldsv Oh cool, can you edit PDFs interactively in the browser with the new version? And are these then also saved? :)

Can I test the app in advance? And how do I do that? 

I am so happy :)

**Comment by skjnldsv** [comment]
> Can I test the app in advance? And how do I do that?

You can download this pull request's zip https://github.com/nextcloud/files_pdfviewer/archive/deps/v2.6.347.zip
Then replace the app manually in your nextcloud instance, and edit the appinfo/info.xml nextcloud versions to fit your current Nextcloud instance version (20 or 21 I assume)

It should work™ :grin: 

> Oh cool, can you edit PDFs interactively in the browser with the new version? And are these then also saved? :)

Haven't tested the edit method, how should I check this? @salcromic

**Comment by salcromic** [comment]
Hi @skjnldsv, first of all thank you, the new version is great :). I would like to excuse the late answer, but I have tested the new version extensively and have a total of 4 suggestions and requests :). 

1. if you edit an interactive PDF in the browser, which works now :), close and open the PDF again, the already entered data is unfortunately not saved. It would be nice if the PDF viewer would save edited PDFs when closing them in future.... :)
2. due to the new version, it takes a long time to load a PDF.
3. the icons in the menu bar (when you have a PDF open) are not displayed.
4. if you want to print a PDF, this is output incorrectly.

-> to point 1: At https://www.collie-it.de/wp-content/uploads/2018/11/MusterBox.pdf you will find an interactive PDF, simply load this into the Nextcloud and test it. I think it is a very cool feature :)

**Comment by skjnldsv** [comment]
> * It would be nice if the PDF viewer would save edited PDFs when closing them in future.

Unfortunately that is no available at the moment I'm not even sure it is possible :shrug: 



> * the icons in the menu bar (when you have a PDF open) are not displayed.

They are displayed for me.

> * if you want to print a PDF, this is output incorrectly.

I can reproduce! Can you open an issue please? :)
Capture d’écran_2021-02-23_09-37-24

**Pull request merged**
