### PR TITLE
Disable content copy for PDF files that specify it

### PR DESCRIPTION
**Pull request by danxuliu**
In v2.5.207 [pdf.js added the "enablePermissions" option to disable copying in the viewer for the PDF files that specify it](https://github.com/mozilla/pdf.js/pull/11789/commits/8521f70157769d9691ee41b03d40b663e3c57e16). The option is off by default, so it needs to be explicitly enabled.

Note that the content copy is prevented just by disabling selection through CSS. The "selection disabled" flag in a PDF document is not a strong security measure and can be easily circumvented (for example, just downloading the file and opening it in a PDF reader that does not honour the flag), so disabling the selection through CSS was deemed good enough for pdf.js.

## How to test
- Upload any PDF file that restricts copy to Nextcloud (for example [the first file](http://www.sstb.se/Homepage/Download-File/f/161759/h/6bc6229975f4c76695ee17246c645a86/Engelsk+svensk+ordlista%2C+version+2.1) in the [related Firefox bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=792816))
- Open the file
- Try to select some text

### Result with this pull request
The text can not be selected

### Result without this pull request
The text can be selected

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]

**Comment by danxuliu** [comment]
Not backported to `stable19` as the feature was introduced in pdf.js 2.5.207 but `stable19` only has pdf.js 2.1.266.

**Pull request merged**
